eagles-project/mam4xx

.github/workflows/auto_test.yml, CMakeLists.txt, README.md, setup
=> Added code coverage instrumentation and reporting

.github/workflows/pnnl_push_mirror.yml
Closes #131 
cc @jeff-cohere @jaelynlitz
=> Upgrade to Ubuntu 22 for push mirror

src/mam4xx/CMakeLists.txt
Just a minor fix for compiling EAMxx.
=> nucleate_ice.hpp is now properly installed.

src/mam4xx/water_uptake.hpp, src/validation/water_uptake/CMakeLists.txt, src/validation/water_uptake/modal_aero_kohler.cpp, src/validation/water_uptake/water_uptake_driver.cpp
This PR brings in a port of the modal_aero_kohler function.
=> Second part of water uptake. 

src/mam4xx/water_uptake.hpp, src/validation/water_uptake/CMakeLists.txt, src/validation/water_uptake/modal_aero_water_uptake_rh_clearair.cpp, src/validation/water_uptake/modal_aero_water_uptake_wetaer.cpp, src/validation/water_uptake/water_uptake_driver.cpp
This PR brings in a port of two more functions from water_uptake. In particular: 
- modal_aero_water_uptake_rh_clearair
- modal_aero_wateruptake_wetaer
=> Third part of water uptake

src/mam4xx/wang2008.hpp
See #211 for the original PR. @mahf708 , FYI, I'm incorporating your commit into this PR.
Closes #210
=> fix second-order PBL nucleation rate

src/mam4xx/water_uptake.hpp, src/validation/water_uptake/CMakeLists.txt, src/validation/water_uptake/modal_aero_water_uptake_dryaer.cpp, src/validation/water_uptake/water_uptake_driver.cpp
This is the fourth PR associated with water uptake. It provides a port of the `modal_aero_water_uptake_dryer` subroutine.
=> Water uptake part 4.

src/tests/mam4_ndrop_unit_tests.cpp
Very minor and self explanatory 🙂
Long overdue in response to comment from #172
=> swap to {fmt} syntax in ndrop unit test

src/mam4xx/water_uptake.hpp
This small PR is associated with but not dependent upon the small Haero PR currently in the pipeline.
=> Adjusting a header path to work both in standalone and EAMxx builds.

src/mam4xx/mam4.hpp, src/mam4xx/mo_chm_diags.hpp, src/validation/mo_chm_diags/CMakeLists.txt, src/validation/mo_chm_diags/chm_diags.cpp, src/validation/mo_chm_diags/het_diags.cpp, src/validation/mo_chm_diags/mo_chm_diags_driver.cpp
work in progress, most of the typing has been done, but haven't had the chance to fine tune/fix all compile errors.
cc @mjs271 @odiazib
=> Validation testing for chm_diags (from mo_chm_diags)

src/mam4xx/mo_photo.hpp, src/validation/mo_photo/CMakeLists.txt, src/validation/mo_photo/compare_set_ub_col_mam4xx_mam4.py, src/validation/mo_photo/mo_photo_driver.cpp, src/validation/mo_photo/set_ub_col.cpp, src/validation/validation.cpp, src/validation/validation.hpp
Not many chemistry subroutines left after this!
=> Ported set_ub_col and setcol

src/mam4xx/tropopause.hpp, src/validation/tropopause/CMakeLists.txt, src/validation/tropopause/tropopause_driver.cpp, src/validation/tropopause/twmo.cpp
=> `twmo`: validation and source code for twmo in tropopause

src/mam4xx/ndrop.hpp
Scream does strong const checking of Kokkos views so modified the input only views of dropmixnuc to be const data.
Fix an index out-of-bounds error.
=> Fixes for Scream integration.

CMakeLists.txt, src/CMakeLists.txt
This is similar to the PR I just merged for haero.
=> Added an option for enabling/disabling tests

src/tests/atmosphere_utils.cpp, src/validation/hetfrz/hetfrz_rates_1box.cpp
This depends on a pull request to the haero repository so needs to be synchronized with that pull request and can not be merged until the haero change is merged to master.
=> Add Interface Pressure to atmosphere class.

src/mam4xx/modal_aer_opt.hpp
These changes are needed for the aerosol optics interface.
=> optics - update interface for calcsize

src/mam4xx/modal_aer_opt.hpp
PR fixing clang-format after PR #313.
=> Fixing  clang-format

.github/pnnl-ci/README.md
reorganized docs for CI and added more detail about which tokens are generated where etc
=> Update docs for CI token maintenance

src/mam4xx/aero_modes.hpp, src/mam4xx/hetfrz.hpp, src/mam4xx/ndrop.hpp, src/mam4xx/nucleate_ice.hpp, src/mam4xx/utils.hpp, src/validation/hetfrz/hetfrz_rates_1box.cpp, src/validation/ndrop/dropmixnuc.cpp, src/validation/nucleate_ice/compute_tendencies.cpp
While working on the ACI codes, I need to make several changes to the MAM4xx. Most of these changes are related to indexing. I also swapped the dimensions of `factnum` so that I could slice it using `subview`.
=> MAM4xx changes needed for the ACI process

src/mam4xx/convproc.hpp
Steps towards a warning free eamxx build.
=> Fix warnings due to signed/unsigned integer comparison

src/mam4xx/wet_dep.hpp
`qqcw` (mmr of cloud borne aerosols)was not updated. This PR adds the code to update `qqcw`
=> Update qqcw in wet scavenging code

src/mam4xx/aer_rad_props.hpp, src/mam4xx/modal_aer_opt.hpp
xref https://github.com/E3SM-Project/scream/pull/2911
=> fix compilation errors 

src/mam4xx/wet_dep.hpp
Add decorator to inline function
Closes #390
=> add KOKKOS_INLINE_FUNCTION to wetdep::init_scavimptbl()

src/mam4xx/ndrop.hpp, src/validation/ndrop/CMakeLists.txt
@singhbalwinder found a bug in the computation of dz. We also decided to modify the code to closely match the Fortran version of ndrop.
=> Fixing dz computation

src/mam4xx/mo_drydep.hpp, src/mam4xx/mo_gas_phase_chemdr.hpp, src/mam4xx/mo_photo.hpp, src/mam4xx/utils.hpp, src/mam4xx/wet_dep.hpp, src/validation/aero_model/aero_model_wetdep.cpp, src/validation/mo_drydep/calculate_gas_drydep_vlc_and_flux.cpp, src/validation/mo_drydep/drydep_xactive.cpp
It was mainly a team.barrier in the right place but fixed some other things along the way.
=> Fix a non bit-for-bit error in E3SM.

src/mam4xx/mo_drydep.hpp, src/mam4xx/mo_gas_phase_chemdr.hpp, src/mam4xx/mo_photo.hpp, src/validation/mo_drydep/calculate_gas_drydep_vlc_and_flux.cpp, src/validation/mo_drydep/drydep_xactive.cpp
Use real arrays for dvel and dflx, and move the initialization of photo to the Emaxx interface.
=> Frontier fix. 

.github/actions/show-workflow-trigger/action.yml, .github/workflows/at2_gcc-cuda.yml, .github/workflows/at2_snl.yml, .github/workflows/clang-format-check.yml, .github/workflows/gh_auto_test.yml, .github/workflows/m4x_autotester_main.yml
Cleaning up a few last details related to manually-triggered workflows
Once again, this needs to be merged to main to test certain functionality--will not affect general autotesting.
=> Modifications to AT2 Manual Trigger

CMakeLists.txt, ext/CMakeLists.txt
This is related to the other PRs in Skywalker and haero that aims to fix the build for the AT2 container along with other tiny fixes
=> Fixes AT2 build and also transient cmake race condition for skywalker

src/mam4xx/mo_gas_phase_chemdr.hpp, src/mam4xx/mo_sethet.hpp, src/mam4xx/mo_setsox.hpp, src/tests/mam4_ndrop_unit_tests.cpp, src/validation/aerosol_optics/aer_rad_props_lw.cpp, src/validation/aerosol_optics/modal_aero_lw.cpp, src/validation/mo_setinv/setinv_test_single_level.cpp, src/validation/mo_setsox/setsox_test.cpp, src/validation/mo_setsox/setsox_test_nlev.cpp, src/validation/modal_aero_amicphys_subareas/form_gcm_of_gases_and_aerosols_from_subareas.cpp, src/validation/modal_aero_amicphys_subareas/set_subarea_gases_and_aerosols.cpp, src/validation/modal_aero_amicphys_subareas/set_subarea_qmass_for_cldbrn_aerosols.cpp, src/validation/modal_aero_amicphys_subareas/set_subarea_qmass_for_intrst_aerosols.cpp, src/validation/modal_aero_amicphys_subareas/set_subarea_qnumb_for_cldbrn_aerosols.cpp, src/validation/modal_aero_amicphys_subareas/set_subarea_qnumb_for_intrst_aerosols.cpp, src/validation/modal_aero_amicphys_subareas/set_subarea_rh.cpp, src/validation/ndrop/maxsat.cpp
And there were a few compile warnings about unused variables.
=> Adding diagnostics for so4 aqueous chemistry and h2so4 uptake.

src/mam4xx/aero_model.hpp, src/mam4xx/mo_gas_phase_chemdr.hpp
This is not a fix yet for the 'Bad file descriptor' error in Frontier, but rather a temporary workaround to make this code work.
=> Bad file descriptor in Frontier

src/mam4xx/mam4_amicphys.hpp, src/mam4xx/mo_gas_phase_chemdr.hpp
Fixing [issue 468]( https://github.com/eagles-project/mam4xx/issues/468 ) @bartgol
=> Using TeamVectorRange and fixing issue #468.
