- src/tests/CMakeLists.txt
See [this Haero issue](https://github.com/eagles-project/haero/issues/435) for details. We're getting rid of the `CreateUnitTest` CMake function in favor of `EkatCreateUnitTest`, since the former was developed when Haero was the primary deliverable (and no longer has all the contextual information it needs to serve its original purpose).
> Switching from CreateUnitTest -> EkatCreateUnitTest.

- src/mam4xx/aero_config.hpp
- src/mam4xx/aging.hpp
- src/mam4xx/coagulation.hpp
- src/tests/mam4_aging_unit_tests.cpp
- src/tests/mam4_coagulation_unit_tests.cpp
- src/validation/aging/mam_pcarbon_aging_1subarea.cpp
- src/validation/aging/mam_pcarbon_aging_frac.cpp
- src/validation/coagulation/coag_1subarea.cpp
- src/validation/coagulation/coag_aer_update.cpp
This PR ties up some loose ends from coagulation and aging. In particular, the variable max_coagpair which defines the maximum number of coagulation pairs is now defined in aero_config.hpp. Additionally,  a unit test is added for both the aging and coagulation classes to guarantee that max_coagpair is not changed to be inconsistent with the value expected in both of those classes.
> Move max_coagpair

- .github/pnnl-ci/pnnl.gitlab-ci.yml
These rules are no longer checked because of how the push mirror triggers the gitlab pipelines
> Remove redundant rules (bc of push mirror)

- CMakeLists.txt
- cmake/add_memcheck_target.cmake
I considered having our CI tests run with Valgrind/memcheck, but some of the cross-validation tests take a very long time with this. If running tests with Valgrind is interesting to us, we might consider altering some of the larger cross-validation tests, like `run_vehkamaki2002_fig8`, which generates a contour plot of the nucleation rate as a function of 2 variables.
> Adds a `make memcheck` target that runs tests with Valgrind.

- src/validation/rename/find_renaming_pairs.cpp
Looks like `mass_2_vol` is set but unused and the warning -> error is crashing the autotester. This should fix it up.
> comment unused variable in `find_renaming_pairs.cpp` to fix autotester fails

- .github/workflows/auto_test.yml
This PR makes it so only one of our builds attempts to upload code coverage reports.
> Fixing a possible race condition in uploading code coverage reports.

- src/mam4xx/aging.hpp
In mam4xx/aging.hpp [L340](https://github.com/eagles-project/mam4xx/blob/da15b2f7722af8ac1c91df149253a38ccef9f657/src/mam4xx/aging.hpp#L340),  mam4xx  calls `transfer_cond_coag_mass_to_accum`, but fortran/aging uses `transfer_aged_pcarbon_to_accum` see [L1784](https://github.com/eagles-project/e3sm_mam4_refactor/blob/26913eb0ffd0fb42cbaa0613f4ea0acec6524d93/components/eam/src/chemistry/modal_aero/modal_aero_amicphys.F90#L1784).
> aging - update function call  to match fortran code.

- src/validation/aging/CMakeLists.txt
After PR #148 we need to update error tolerances in aging. I used the python ``compare_mam4xx_mam4.py`` script from [mam_x_validation/scripts](https://github.com/eagles-project/mam_x_validation/blob/36a3f9e9351fa46b0438158f8e7c29521c7cc35d/scripts/compare_mam4xx_mam4.py) to compute and check the L1/L2/Linf norms.  Threshold errors are set to smaller error that make the test pass.
> aging - validation tests update

- README.md
- docs/installation.md
- src/mam4xx/aero_modes.hpp
- src/mam4xx/kerminen2002.hpp
- src/mam4xx/merikanto2007.hpp
- src/mam4xx/nucleation.hpp
- src/mam4xx/vehkamaki2002.hpp
- src/mam4xx/wang2008.hpp
- src/tests/mam4_gasaerexch_unit_tests.cpp
- src/tests/mam4_nucleation_unit_tests.cpp
- src/validation/gasaerexch/CMakeLists.txt
Ran across a few of these lately and figured why not get rid of them. Most were in comments or something latex-y. And it appears that cmake doesn't get too grumpy about them.
> remove non-ascii characters from mam4xx

- .gitignore
- src/tests/CMakeLists.txt
- src/tests/kohler_unit_tests.cpp
- src/tests/kohler_verification.cpp
This PR is a small housekeeping one that moves, `mam4_test_config.hpp`, the configure file that's generated by `mam4_test_config.hpp.in`, out of the source tree and into `${PROJECT_BINARY_DIR}/include/`.
> Move `mam4_test_config.hpp` out of source tree

- .github/pnnl-ci/ci.sh
- .github/pnnl-ci/findIdleDLNodes.pl
List of GPU partitions is now given and gcc 10 is now being used on deception - see https://github.com/eagles-project/haero/pull/451 for the associated HAERO PR
> Expand GPU partitions and fix PNNL CI

- src/mam4xx/CMakeLists.txt
Eamxx can't find `libmam4xx.a` because it's installed behind an extra `mam4xx` folder.   This PR removes that folder from the Mam4xx library install path.
> removing redundant mam4xx folder from library install location

- src/mam4xx/convproc.hpp
- src/validation/convproc/CMakeLists.txt
- src/validation/convproc/convproc_driver.cpp
- src/validation/convproc/ma_precpevap_convproc.cpp
- src/validation/convproc/ma_precpprod.cpp
First case of running into a level-dependent process that has to be evaluated from the top level to the bottom because the computation of level n depends on the results of level n-1.  To complicate it a bit more the data at each level is itself an array of data of undetermined length making it a 2D array that needs to be sub-viewed at each level. So my first use of Kokkos::subview in mam4xx.
> Add C++ version of ma_precpevap_convproc and tests.

- src/mam4xx/hetfrz.hpp
This is a tiny fix that @pressel mentioned before going on leave last Friday. It shouldn't affect any of our tests.
> Corrected name of hetfrz parameterization.

- src/mam4xx/convproc.hpp
- src/tests/mam4_convproc_unit_tests.cpp
- src/validation/convproc/CMakeLists.txt
- src/validation/convproc/compute_ent_det_dp.cpp
- src/validation/convproc/compute_massflux.cpp
- src/validation/convproc/compute_midlev_height.cpp
- src/validation/convproc/compute_wetdep_tend.cpp
- src/validation/convproc/compute_wup.cpp
- src/validation/convproc/convproc_driver.cpp
- src/validation/convproc/initialize_tmr_array.cpp
- src/validation/convproc/update_qnew_ptend.cpp
@jeff-cohere ,
I would like to get this branch merged into main so I could continue to add functions without bloating an already large merge request.  I would have already merged but for a problem with a couple of Skywalker validation tests which are commented out in the CMakeLists.txt file. I'm working with Balwinder to figure out why my results differ from the e3sm Skywalker python files and my best guess at this point is that the e3sm Skywalker files need to be regenerated.  
There are quite a few functions added, some of which could be parallel over layers within a column and some not.  I've added comments at the top of the functions for how parallelizable the function is:
* Some functions apply a non-trivial algorithm (non-associative, non-binary operator) to the previous layer to …
> Add a few convproc functions and tests.

- src/mam4xx/nucleation.hpp
These changes allow our eamxx-mam4xx column test to compare closely with the MAM4 box model's ["smoke test"](https://github.com/eagles-project/mam_refactor/blob/main/standalone/tests/smoke_test.nl). However, they seem to cause a failure in our [amicphys unit test](https://github.com/eagles-project/mam4xx/blob/main/src/tests/mam4_amicphys_1gridcell.cpp).
@overfelt , I'm curious if you have any thoughts about this other than what we've (briefly) discussed. I'm fairly confident that these fixes to the nucleation parameterization are needed, but I don't know if I've missed something that might also be necessary for the amicphys test to pass.
After this, we can focus more on the simulation described in #169
> Fixed several issues in the calculation of nucleation tendencies

- CMakeLists.txt
So, to my surprise, when builds weren't working out properly for me, I realized that the machine I was using was running an old version of cmake, and that fact was not caught by the `cmake_minimum_required (VERSION 3.17.0)`. As it turns out, the spacing (lack of) is rather important 🙃
Working properly now.
> bugfix--spacing in top-level CML.txt `cmake_minimum_required()`

- src/tests/atmosphere_utils.cpp
- src/validation/hetfrz/hetfrz_rates_1box.cpp
This is a companion PR to a Haero PR with the same purpose. NOTE: this PR will fail until the Haero PR goes in.
> Adding new argument to Atmosphere constructors in tests.

- src/mam4xx/CMakeLists.txt
I am trying to keep our eamxx integration work up to date with the haero and mam4xx repos, and occasionally I discover that we're not installing everything we need for eamxx. :-)
> This tiny fix makes sure mam4xx's gas chemistry headers are installed.

- src/mam4xx/wang2008.hpp
This small PR fixes an issue with the Wang et al 2008 second-order PBL nucleation process.
For it to be second order, the H2SO4 term must be squared. See the reference [implementation in EAM's MAM](https://github.com/E3SM-Project/E3SM/blob/4fb8eddcf457d18d5619dd4a1c4785ed7c45f725/components/eam/src/chemistry/modal_aero/modal_aero_newnuc.F90#L1216C1-L1223C15) as well as the the [cited paper](https://doi.org/10.5194/acp-9-239-2009). 
Fix #210 
This bug was first identified in the review of a PR to EAMxx, xref https://github.com/E3SM-Project/scream/pull/2429.
> fix second-order PBL nucleation rate

- .github/pnnl-ci/ci.sh
- .github/workflows/auto_test.yml
- CMakeLists.txt
- setup
- src/mam4xx/CMakeLists.txt
- src/mam4xx/aero_config.hpp.in
- src/mam4xx/convproc.hpp
- src/mam4xx/mo_photo.hpp
- src/mam4xx/ndrop.hpp
- src/mam4xx/wet_dep.hpp
- src/tests/CMakeLists.txt
Because of the way we use automatic C++ arrays in some of our parameterizations, it is necessary for us to have the number of vertical levels as a compile-time constant. While this is undesirable in an ideal situation, it's actually fine in the short term because EAMxx also has a compile-time-configured number of vertical levels.
mam4::nlev now contains the number of vertical levels used internally within mam4xx's C++ parameterizations.  I haven't changed any of the test or validation code to set the number of vertical levels to mam4::nlev, since that would imply that we have datasets for other numbers of vertical levels. To make it possible for us to run validations tests in situations where mam4::nlev != 72, I have added the constraint that mam4::nlev >= 72. As long as we are zeroing …
> Adds NUM_VERTICAL_LEVELS as a CMake parameter that defines mam4::nlev.

- src/mam4xx/gas_chem.hpp
- src/mam4xx/gas_chem_mechanism.hpp
In an effort to create a case in which the Newton-Raphson solve in `gas_chem.hpp` fails, I ended up having to go through most of that file and also `gas_chem_mechanism.hpp` to get things straight in my own head. I added a bunch of explanatory comments and also some spots where computational weirdness appeared to be ocurring.
In doing that, I noticed that, from a perspective of units consistency, there are some very strange-looking arithmetic calculations being done. I put a `FIXME` at the ones I spotted along with some salient details. Note that, it's ***possible*** that everything is ok, but that would seem to require the `base_solution`, `solution`, etc., arrays to be carrying quantities with differing units and/or the same for the reaction rates (`lrxt`, `rxt`) or washout rates(?) …
> Add Comments and Concerns to gas_chem, plus one minor fix

- docs/clang-format.md
- docs/development.md
- docs/dot_envrc.md
- docs/installation.md
Added a cleaned up version of the message I previously sent in slack. I retained the bit about `direnv` since it could be useful, but not sure if it belongs here and can ditch it if not. Also added bash syntax specifiers to a few code blocks that I noticed while scrolling around.
> Add a page to the docs explaining how to get `clang-format` v14 via Homebrew

- src/mam4xx/CMakeLists.txt
Found this omission when I updated the mam4xx submodule in EAMxx.
> wet_dep.hpp is now installed.

- src/mam4xx/aero_config.hpp.in
For now, I'm just adding the container. When it's appropriate, we can add sources to the appropriate interfaces.  On the mam4xx side, we can assume that e.g. emissions data are placed properly within Sources. On the EAMxx side, we must make sure that such source data are properly interpolated from files, etc.
> Adding a Sources container for storing surface and volume sources.

- src/mam4xx/gasaerexch.hpp
- src/mam4xx/gasaerexch_soaexch.hpp
The qaer array should be indexed with aerosol ids and not gas ids as are most of the arrays in these functions. There is an array, gas_to_aer, that maps between the two.
This was not needed before because for the MAM4 model we are using the AeroId SOA and GasId SOAG are both 0 so it did not matter that that gas was used to index the aerosol.
> Fix indexing of qaer array in gasaerexch_soaexch.hpp.

- src/tests/mam4_amicphys_1gridcell.cpp
NH3 is not supported but was turned on because an
index was passed where a bool was expected.
Fixes a certain Valgrind error.
> Correctly turn off use of NH3.

- src/mam4xx/aero_config.hpp.in
- src/mam4xx/aero_modes.hpp
- src/mam4xx/gasaerexch.hpp
- src/mam4xx/gasaerexch_soaexch.hpp
- src/tests/mam4_amicphys_1gridcell.cpp
- src/tests/mam4_gasaerexch_unit_tests.cpp
- src/validation/gasaerexch/skywkr_gasaerexch_timestepping.cpp
While only two gases (H2SO4 and SOAG) interact directly with aerosols in mam4xx, E3SM's version of MAM4 actually has four other gases that we haven't added to mam4xx yet. These other gases interact only indirectly with aerosols via the chemical mechanism we're porting.
This PR adds the other four gases to mam4xx. It also adds `None` enums for mode indices and gas ids, like aerosol ids have. This allows us to use integer indices to indicate that something is not a valid gas/aerosol/mode index, which is important because MAM4 routinely stuffs all of these quantities interchangeably into arrays as part of its spaghetti design pattern.
> Adding more gas IDs to reflect E3SM's MAM4 configuration.

- README.md
- docs/development.md
- docs/installation.md
I'm just making a few adjustments. Let me know if you want me to update anything else.
> Some very minor updates to documentation.

- src/mam4xx/aero_config.hpp.in
- src/mam4xx/aging.hpp
- src/mam4xx/coagulation.hpp
- src/mam4xx/convproc.hpp
- src/mam4xx/nucleate_ice.hpp
- src/mam4xx/nucleation.hpp
- src/mam4xx/rename.hpp
- src/mam4xx/wet_dep.hpp
This PR uses the new GPU-sensible `min()`, `max()`, and `epsilon()` functions offered by Haero. It also annotates some more functions with `KOKKOS_INLINE_FUNCTION` to make them callable on-device.
> More GPU-related fixes

- src/mam4xx/mo_photo.hpp
- src/validation/mo_photo/table_photo.cpp
This PR adds a column-independent struct called `PhotoTableData` that stores all the data used to interpolate photolysis rates, and a column-specific struct called `PhotoTableWorkArrays` that contains views that function as work arrays. These two types encapsulate array data that once lived in Fortran module variables. I find it too hard to work with functions with 87 arguments, so this is how I've been dealing with them. :-)
No logic is changed, apart from the order of allocation of views. I hope this will allow me to simplify the photolysis code in our EAMxx aerosol microphysics process.
> Adding some basic data types to simplify photolysis rate calculations

- src/mam4xx/mo_photo.hpp
This change lets us use `phtcnt` to size arrays on the GPU.
> Changed phtcnt from a Real to an int.

- src/mam4xx/lin_strat_chem.hpp
It turns out that the work in the `lin_strat_sfcsink` function is independent of levels in the sense that none of the work in a level `k` depends on work in another level `k`, and that there's an accumulation that is order-independent. It also turns out that it's better for us to be able to call this function in the context of a single vertical level, rather than as a whole-column operation. This PR adds a new single-level version of the function.
> Added a single-level version of lin_strat_sfcsink.

- src/mam4xx/CMakeLists.txt
- src/mam4xx/mam4.hpp
- src/mam4xx/mo_setinv.hpp
- src/validation/CMakeLists.txt
- src/validation/mo_setinv/CMakeLists.txt
- src/validation/mo_setinv/mo_setinv_driver.cpp
- src/validation/mo_setinv/setinv_test_nlev.cpp
- src/validation/mo_setinv/setinv_test_single_level.cpp
This PR ports `mo_setinv`, which sets the "invariant species" within [`mo_gas_phase_chemdr.F90`](https://github.com/eagles-project/e3sm_mam4_refactor/blob/f6f291b80b9e245a04d422e7bcda5a9609c12107/components/eam/src/chemistry/mozart/mo_gas_phase_chemdr.F90#L375).
There are some idiosyncratic constants and indexing schemes that are used on the fortran side, and I'm not sure some of these will make it into EAMxx. For example, there's some convoluted combination of strings and indices used to get the `cnst_offline` quantities from some faraway source. So, I've stored these variables in a `Config` struct for now that's initialized in `setinv()` and passed as an argument to `setinv_single_level()`. 
There are two validation tests, `setinv_test_single_level.cpp` that runs data for a number of …
> Long-awaited Port of `mo_setinv`

- src/mam4xx/utils.hpp
This PR makes a copy of the following functions from [mam_coupling](https://github.com/eagles-project/scream/blob/2d2180dfdd67eac8cf76efdb773428e6c0117181/components/eamxx/src/physics/mam/mam_coupling.hpp#L710) :
`transfer_prognostics_to_work_arrays`, `transfer_work_arrays_to_prognostics`,` convert_work_arrays_to_vmr`, and `convert_work_arrays_to_mmr`.
> mam_coupling- move code from eamxx to mam4xx

- .github/pnnl-ci/ci.sh
- .github/pnnl-ci/pnnl.gitlab-ci.yml
PNNL HPC staff reported 1000 nvcc calls in a recent pipeline, and so instead of the `cmake --build build -- -j` I have updated that command to be limited to 8 cores. Might slow things down a little, but will prevent this job fork bombing any shared nodes...
> limit cmake core count

- src/mam4xx/ndrop.hpp
Prints a message about the Geopotential height not being decreasing as the ndrop algorithm divides by the difference in two adjacent levels.
> Add check to throw on divide by zero.

- src/mam4xx/aero_model.hpp
- src/mam4xx/ndrop.hpp
- src/mam4xx/wet_dep.hpp
- src/validation/wetdep/compute_tendencies.cpp
Wet deposition has loops within loops within loops
with column levels within species within phase
within modes. Previously I had tried to put the outer loop
to be the levels as this was the approach at the time.
This resulted in awkward code and restrictions
on the number of threads that could be run.
Now the inner loop is over levels with outer loops are over
modes, phases and species.  This requires a lot of parallel_for
loops on teams but since it is all within compute_tendencies
which is already on device, these are not a kernel launches
and should be just as fast as before.
> Refactor the main loops within Wet Deposition.

- CMakeLists.txt
- src/mam4xx/CMakeLists.txt
This is the last missing piece of the puzzle for CIME-enabled builds. This PR should go in after the corresponding Haero PR, after which we can reset the haero and mam4xx submodules in our SCREAM fork to their respective `main` branches.
Closes #290
> Allows mam4xx to be built as part of a larger CMake project

- src/mam4xx/mo_drydep.hpp
- src/validation/mo_drydep/CMakeLists.txt
- src/validation/mo_drydep/calculate_resistance_rlux.cpp
Turned out to be a combined issue of a practically invisible indexing issue and initializing the output variable, `rlux` to zero to avoid pesky `NaN`s.
This is step 1 of addressing the failing `drydep_xactive` test.
Not tested on gpu yet, but will get there shortly.
> Fixed failing test for `mo_drydep::calculate_resistance_rlux()`

- src/mam4xx/aero_model.hpp
- src/mam4xx/convproc.hpp
- src/mam4xx/drydep.hpp
- src/mam4xx/modal_aer_opt.hpp
- src/mam4xx/ndrop.hpp
- src/mam4xx/water_uptake.hpp
- src/mam4xx/wet_dep.hpp
- src/tests/mam4_convproc_unit_tests.cpp
- src/tests/mam4_ndrop_unit_tests.cpp
- src/validation/aerosol_optics/aer_rad_props_lw.cpp
- src/validation/aerosol_optics/aer_rad_props_sw.cpp
- src/validation/aerosol_optics/modal_aero_lw.cpp
- src/validation/aerosol_optics/modal_aero_sw.cpp
- src/validation/calcsize/modal_aero_calcsize_sub.cpp
- src/validation/convproc/compute_tendencies.cpp
- src/validation/convproc/initialize_tmr_array.cpp
- src/validation/convproc/ma_convproc_dp_intr.cpp
- src/validation/convproc/ma_convproc_tend.cpp
- src/validation/convproc/ma_precpevap_convproc.cpp
- src/validation/convproc/ma_precpprod.cpp
- src/validation/convproc/ma_resuspend_convproc.cpp
- src/validation/convproc/update_qnew_ptend.cpp
- src/validation/convproc/update_tendency_final.cpp
- src/validation/drydep/aero_model_drydep.cpp
- src/validation/drydep/compute_tendencies.cpp
- src/validation/ndrop/ccncalc.cpp
- src/validation/ndrop/dropmixnuc.cpp
- src/validation/ndrop/get_activate_frac.cpp
- src/validation/water_uptake/modal_aero_water_uptake_dr_col.cpp
- src/validation/wetdep/compute_tendencies.cpp
The classes that set a gas_pcnst from aero_model::gas_pcnst in public header data were changed to use the one from aero_model directly. Clean up the code a bit.
Note that there is a gas_pcnst in gas_chemistry that is set to 31. The one in aero_model is set to 40 and it might be a bit confusing.
> Trivial change to use aero_model::gas_pcnst.

- src/mam4xx/mo_drydep.hpp
- src/validation/mo_drydep/CMakeLists.txt
This fixes the `calculate_gas_drydep_vlc_and_flux()` test, which is now passing with a tolerance of 1e-10.
It turns out that the input yaml files for the 4 sub-cases (that compose the single, merged test case) contained a small error. The variable `lcl_frc_landuse` in the input yaml file was for a 4-column chunk (4 columns x `n_land_type = 11`), rather than a single column like the remainder of the data. As a result, the test code was not reading the `lcl_frc_landuse` values that corresponded to the rest of the provided variables, since it was likely reading the first 11 values in the flattened array.
Additionally, the resulting `mam_calculate_gas_drydep_vlc_and_flux.py` validation file also appeared to be in error for the same reason (I hope 🤞). I found both of these bugs by running the …
> Fix calculate_gas_drydep_vlc_and_flux() test

- src/mam4xx/gasaerexch.hpp
- src/mam4xx/mo_setsox.hpp
Balwinder has a branch in which he changes the ordering of aerosols within modes. This should not make a difference but an extra call to aerosol_index_for_mode was breaking Gas/Aerosol exchange in this case.  Once this fix is merged into Balwinder's branch, it should fix his tests.
> Fix for reordering of aerosols within modes.

- src/mam4xx/gasaerexch_soaexch.hpp
one-liner to fix compile error on gcc 12.1
```shell
gasaerexch_soaexch.hpp:168:8: error: 'tot_frac_single_soa_species' may be used uninitialized [-Werror=maybe-uninitialized]
```
> fix compile Werror in gasaerexch_soaexch.hpp

- src/mam4xx/aero_modes.hpp
- src/validation/calcsize/compute_dry_volume.cpp
- src/validation/calcsize/compute_tendencies.cpp
- src/validation/validation.hpp
Species order is revised to match MAM4 in E3SMv2. This should help us in making a direct comparison with MAM4 codes and output files.
> Changes species order to match MAM4 in E3SMv2

- src/mam4xx/aer_rad_props.hpp
- src/validation/aerosol_optics/volcanic_cmip_sw.cpp
We encountered a race condition in the CIME case involving the `SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.chrysalis_intel.scream-mam4xx-optics `(D is for debug) and the` eamxx-multi-process` test (`homme_shoc_cld_p3_mam_optics_rrtmgp`). This issue was reproducible on multiple machines with different compilers. The race condition only occurred with the debug build type and multiple threads. I discovered that switching the for loop to Kokkosparallel_fors resolves this race condition. As a precaution, I added a` Kokkos::single` over `tropopause_or_quit`, which is serial routine.
Switching the for loop to` Kokkos::parallel_for`s will improve performance. However, it is unclear why our eamxx test only failed with the debug build type and multiple threads on the host.
> aerosol_optics - switching for to Kokkos::parallel_fors.

- src/mam4xx/aer_rad_props.hpp
This PR fixes NaN values in the eamxx-optics tests; see also PR #318.
> Removing Kokkos::single. 

- CMakeLists.txt
We would like to be able to build the entire eamxx project with shared libs enabled, so making the change here.
There may be other changes needed elsewhere, but for now, I believe this is all that is needed.
Putting this PR together so that you can see how this affects your CI and so on.
Tagging @jeff-cohere @singhbalwinder @odiazib @bartgol
> enable shared libs build

- CMakeLists.txt
MAM4xx assumes that the number of vertical levels is 72 for all model configurations. High-resolution SCREAM has 128 levels. This PR adds logic so that MAM4xx uses the same number of levels as SCREAM if MAM4xx is run under SCREAM.
> Adds logic to use scream number of vertical levels if the MAM4xx is run under scream

- src/mam4xx/aer_rad_props.hpp
- src/mam4xx/aero_config.hpp.in
- src/mam4xx/aero_model.hpp
- src/mam4xx/aging.hpp
- src/mam4xx/calcsize.hpp
- src/mam4xx/coagulation.hpp
- src/mam4xx/drydep.hpp
- src/mam4xx/gasaerexch.hpp
- src/mam4xx/hetfrz.hpp
- src/mam4xx/lin_strat_chem.hpp
- src/mam4xx/mo_chm_diags.hpp
- src/mam4xx/mo_sethet.hpp
- src/mam4xx/mo_setinv.hpp
- src/mam4xx/mo_setsox.hpp
- src/mam4xx/modal_aer_opt.hpp
- src/mam4xx/ndrop.hpp
- src/mam4xx/nucleate_ice.hpp
- src/mam4xx/nucleation.hpp
- src/mam4xx/rename.hpp
- src/mam4xx/wet_dep.hpp
- src/validation/aero_model/aero_model_calcsize_water_uptake_dr.cpp
- src/validation/aero_model/aero_model_wetdep.cpp
- src/validation/aerosol_optics/data_transfer_state_q_qqwc_to_prog.cpp
Changes:
- Use `TeamVectorRange` if only a single level of parallelism exists within a team policy loop. Given the TeamPolicy used in EAMxx for MAM4xx code, I don't think these fixes will solve non-determinism, but if in the future a vector length >1 is used in the TeamPolicy it might be necessary.
- Use `[&]` for the capture in inner parallel loops. This may clear up some compiler errors/warnings on some arch and should be slightly more performant.
- Found a case where a parallel_reduce had the local and global sum variables having the same name. This should work fine, but is confusing.
> Use TeamVectorRange policies

- src/mam4xx/aero_model_emissions.hpp
- src/validation/aero_emissions/CMakeLists.txt
- src/validation/aero_emissions/calc_om_seasalt.cpp
- src/validation/aero_emissions/dust_emis.cpp
- src/validation/aero_emissions/marine_organic_emis.cpp
- src/validation/aero_emissions/marine_organic_massflx_calc.cpp
- src/validation/aero_emissions/marine_organic_numflx_calc.cpp
- src/validation/aero_emissions/seasalt_emis.cpp
- src/validation/aero_emissions/seasalt_emisflx_calc_massflx.cpp
- src/validation/aero_emissions/seasalt_emisflx_calc_numflx.cpp
I mistakenly pushed some updates to `mam_x_validation` that correspond to some working changes in the eamxx integration for `aero_model_emissions`. This adds the new changes to fix the failing tests on main.
> Fix Failing Validation Tests for Online Emissions

- src/mam4xx/nucleation.hpp
- src/tests/CMakeLists.txt
- src/tests/mam4_amicphys_1gridcell.cpp
- src/validation/nucleation/CMakeLists.txt
- src/validation/nucleation/binary_nuc_vehk2002.cpp
- src/validation/nucleation/mer07_veh02_nuc_mosaic_1box.cpp
- src/validation/nucleation/nucleation_driver.cpp
- src/validation/nucleation/pbl_nuc_wang2008.cpp
This PR ports `mer07_veh02_nuc_mosaic_1box()` as the version coming from the MAM refactor repo--in contrast to the box-model version that was already present. A validation test is added for this function, as well as for `binary_nuc_vehk2002()` and `pbl_nuc_wang2008()`.
> Port refactored version of `mer07_veh02_nuc_mosaic_1box()` and add validation tests

- src/mam4xx/gas_chem.hpp
- src/mam4xx/gas_chem_mechanism.hpp
A few more changes are needed for the microphysics branch under EAMxx, which is currently pointing to this branch for the MAM4xx submodule.
> Changes needed for microphysics branch

- src/mam4xx/lin_strat_chem.hpp
The return type is changed so that the function's output is easy to see.
> Changes return type of linoz srf sink function from void to Real

- src/mam4xx/mo_gas_phase_chemdr.hpp
- src/mam4xx/mo_photo.hpp
- src/validation/mo_photo/cloud_mod.cpp
- src/validation/mo_photo/interpolate_rsf.cpp
- src/validation/mo_photo/jlong.cpp
- src/validation/mo_photo/table_photo.cpp
We were encountering an FPE in the pm-gpu configuration of eamxx in [PR 3013](https://github.com/E3SM-Project/scream/pull/3013). To fix this issue, we made the necessary changes to avoid race conditions. However, the mo_photo function will need further modifications to fully utilize parallelism from GPUs.
> Avoid race conditions in the mo_photo functions.

- src/mam4xx/mo_chm_diags.hpp
- src/mam4xx/mo_sethet.hpp
- src/validation/mo_sethet/CMakeLists.txt
- src/validation/mo_sethet/calc_precip_rescale.cpp
- src/validation/mo_sethet/gas_washout.cpp
- src/validation/mo_sethet/sethet.cpp
- src/validation/mo_sethet/sethet_driver.cpp
opened to take over #295 to have a clean starting point to debug from
> Final: `mo_sethet`

- src/mam4xx/mo_drydep.hpp
- src/validation/mo_drydep/CMakeLists.txt
- src/validation/mo_drydep/find_season_index.cpp
- src/validation/mo_drydep/mo_drydep_driver.cpp
- src/validation/validation.cpp
- src/validation/validation.hpp
Implementing the find_season_index routine to encapsulate the interpolation of the season_wes.nc file, from [line 267](https://github.com/eagles-project/e3sm_mam4_refactor/blob/599e772e34a0a32dacadc40688fd091e1f532d76/components/eam/src/chemistry/mozart/mo_drydep.F90#L267) to  [line 318](https://github.com/eagles-project/e3sm_mam4_refactor/blob/599e772e34a0a32dacadc40688fd091e1f532d76/components/eam/src/chemistry/mozart/mo_drydep.F90#L318).
This function is only invoked during initialization and has a small kernel. Thus, only a host version was implemented.
One validation test is implemented, and it is passing with a relative error tolerance of 0. Note that the output of the function (`index_season_lai`) consists of integers. Thus, an error of 0 is required to pass this test.
> Implementing the find_season_index routine

- src/mam4xx/aero_model_emissions.hpp
Minor fix to get things compiling on Weaver.
Required making copies of the offending namespace variables that are local to the `aero_model_emissions()` function call, and then passing the local variables to the lower-level functions.
> fix cuda compile error for `aero_model_emissions`

- src/mam4xx/aero_model_emissions.hpp
Corrected to match `if` branch and ensure the dust indices of `cflux` are properly zeroed-out in the case that `soil_erodibility < soil_erod_threshold`
> Fix else branch indexing in dust_emis()

- src/mam4xx/mo_sethet.hpp
- src/mam4xx/wet_dep.hpp
- src/validation/aero_model/aero_model_wetdep.cpp
With @overfelt knocking out the issues related to the failing tests and non-determinism that's been happening in EAMxx/E3SM, these are the last few things that were required to get it talking to the EAMxx _**wet scavenging**_ interface.
Admittedly, I'm not sure that the use of a local `int isprx[nlev]` array is the most elegant solution, but I'm happy to change this up later.
In favor of getting the EAMxx changes PR'd to the E3SM repo ASAP, I'm going to immediately merge this into `main`, and we can update after winter shutdown if I've done anything super dumb.
Thanks, and have a great holiday break!
@singhbalwinder
@odiazib 
@jaelynlitz
> Change `aero_model_wetdep()` Signature to Correspond to EAMxx Interface

- src/mam4xx/wet_dep.hpp
This appears to fix the out-of-bounds issue that's causing the E3SM standalone wet deposition test to fail.
> fix work array size for wet_dep() and treat isprx as int ptr

- src/mam4xx/mo_sethet.hpp
After the fix to remove the barrier, the result was then incorrect for GPUs. To fix this required calling a certain loop over the levels in a column inside a Kokkos::single because each level would modify other levels. This reading and updating all the levels in every level in parallel does not work.  Has to be done one level at a time and that is what Kokkos:::single does.
> Remove team.team_barrier() that was called inside a conditional if statement.

- src/mam4xx/seq_drydep.hpp
Adds two missing limiters in drydep. The EAMxx code with all processes was crashing due to these missing values at the very first time step. Fortunately, the kernel checks helped diagnose the issue. The Fortran code equivalent for this logic is [here](https://github.com/eagles-project/e3sm_mam4_refactor/blob/refactor-maint-2.0/driver-mct/shr/seq_drydep_mod.F90#L1138-#L1144)
> Adds missing init code for drydep

- src/mam4xx/mo_photo.hpp
Adds missing initialization of `photo` variable (see the Fortran code [here](https://github.com/eagles-project/e3sm_mam4_refactor/blob/refactor-maint-2.0/components/eam/src/chemistry/mozart/mo_photo.F90#L464-L471))
This fix fixes the ERS CIME test when all MAM4xx processes are turned on.
> Adds init for an uninitialzed variable in mo_photo - fixes ERS test

- src/mam4xx/mo_photo.hpp
`t_index` was going negative for extremely low temperatures, causing the simulation to crash. Following the Fortran code (see [here](https://github.com/eagles-project/e3sm_mam4_refactor/blob/refactor-maint-2.0/components/eam/src/chemistry/mozart/mo_jlong.F90#L595-L596)), `t_index` is limited so that it stays positive (i.e., >=0). The simulation passed the crashing point after this change.
> Fixes an index so that it doesn't go negative to mimic Fortran version

- src/mam4xx/aer_rad_props.hpp
- src/mam4xx/modal_aer_opt.hpp
- src/mam4xx/modal_aero_calcsize.hpp
- src/mam4xx/water_uptake.hpp
- src/mam4xx/wet_dep.hpp
- src/validation/aero_model/aero_model_calcsize_water_uptake_dr.cpp
- src/validation/aero_model/aero_model_wetdep.cpp
- src/validation/aerosol_optics/aer_rad_props_lw.cpp
- src/validation/aerosol_optics/aer_rad_props_sw.cpp
- src/validation/aerosol_optics/modal_aero_lw.cpp
- src/validation/aerosol_optics/modal_aero_sw.cpp
- src/validation/calcsize/modal_aero_calcsize_sub.cpp
- src/validation/calcsize/modal_aero_calcsize_sub_ptend.cpp
Creating a calcsize data structure to group the many parameters used by calcsize. Additionally, this allows us to move the initialization of these parameters outside of the main computation kernel.
See also [PR 7161](https://github.com/E3SM-Project/E3SM/pull/7161) in e3sm.
> CalcsizeData struct

- src/mam4xx/drydep.hpp
- src/mam4xx/gas_chem.hpp
Calls to printf will cause compiler errors on Aurora.
> Remove calls to printf on device as SYCL does not support it.

- .github/actions/show-workflow-trigger/action.yml
- .github/workflows/README.md
- .github/workflows/at2_gcc-cuda.yml
- .github/workflows/at2_snl.yml
This adds the AT2 workflow to test on SNL machines.
Currently, the only testing we do with this workflow is for GPU/cuda on H100 cards.
This autotesting workflow is triggered by pull requests to main and by a handful of actions on an open PR to main (e.g., reopened, converted to ready from draft, etc.).
A couple of notes (as I understand things--could be mistaken in minor ways):
- If a PR contains changes to the `.github` directory, a member of the `snl-testing-admins` team must add the `CI-AT2_special_approval` to kick off the autotesting.
- Otherwise, any PR that is submitted by a member of the `snl-testing` team, and only contains commits from members of that team should automatically trigger this autotesting.
- In the case that the PR is submitted by someone who is not a member of the …
> Sets Up Autotesting on SNL Machines

- .github/workflows/at2_snl.yml
Add `/*` wildcards to end of paths since changing a file with only the directory given in the workflow file did not trigger.
It could potentially be a matter of adding trailing `/` character, too, but we'll see...
> alter triggers for AT2 workflow

- .github/workflows/README.md
- .github/workflows/at2_snl.yml
- Enables the cron-based nightly testing trigger.
- Minor edits to the README, as I understand more about how this works.
> Enable cron-based nightly testing and small changes to workflows README

- .github/workflows/AT2-README.md
- .github/workflows/README.md
- .github/workflows/at2_gcc-cuda.yml
- .github/workflows/gh_gcc-cpu.yml
- .github/workflows/m4x_autotester_main.yml
This PR modifies the following:
1. Options for manually-triggered workflows
- More granularity for choosing the type of test--options are now:
- Branch
- Test Machine Architecture
- Current Options:
- `GPU-NVIDIA_H100`
- `CPU-Ubuntu_22-04`
- `ALL`
- Floating-point Precision
- Current Options:
- `single`
- `double`
- `ALL`
- Build Type
- Current Options:
- `Debug`
- `Release`
- `ALL`
- Some helpful resources for setting this up:
- [Workflow Dispatch Inputs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs)
- [Workflow Call Syntax - Inputs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_call)
1. Updates the codecov action to v5
- This wasn't strictly necessary but was a part …
> Usability upgrades for manually-triggered workflows and fix codecov bug

- src/mam4xx/modal_aer_opt.hpp
- src/mam4xx/modal_aero_calcsize.hpp
- src/mam4xx/utils.hpp
- src/mam4xx/water_uptake.hpp
- src/mam4xx/wet_dep.hpp
- src/validation/aero_model/aero_model_calcsize_water_uptake_dr.cpp
- src/validation/aero_model/aero_model_wetdep.cpp
- src/validation/aerosol_optics/aer_rad_props_lw.cpp
- src/validation/aerosol_optics/aer_rad_props_sw.cpp
- src/validation/aerosol_optics/data_transfer_state_q_qqwc_to_prog.cpp
- src/validation/aerosol_optics/modal_aero_lw.cpp
- src/validation/aerosol_optics/modal_aero_sw.cpp
- src/validation/calcsize/modal_aero_calcsize_sub.cpp
- src/validation/calcsize/modal_aero_calcsize_sub_ptend.cpp
I am removing `view.data()` from the `calcisize` routines. I am using a template parameter `VectorType` to replace` Real* var ` because we are using Real arrays a few times.
I compiled and ran the main branch of mam4xx in Frontier, and four validation tests failed:
```
16 - validate_stand_modal_aero_calcsize_sub_update_ptend (Failed)
18 - validate_stand_calcsize_aero_model_wetdep_ts_379 (Failed)
492 - validate_chm_diags_ts_355 (Failed)
524 - validate_gas_washout_merged (Failed)
```
I note that this PR fixes `validate_stand_modal_aero_calcsize_sub_update_ptend` and `validate_stand_calcsize_aero_model_wetdep_ts_379`. Thus, using raw pointers is producing issues in the AMD backend. I will continue replacing .data() in a follow-up PR.
See [PR …
> Removing .data() from calcsize routines.

- src/mam4xx/modal_aer_opt.hpp
For very high-resolution runs, we occasionally encounter small negative values for aerosol dry volume in some grid cells. Although these values are close to zero, they can lead to extremely large results during mathematical operations like division or exponentiation. To prevent this, we introduced a condition that detects small negative dry volumes and skips the subsequent calculations. In such cases, we set all optical parameters to zero.
Another `if` condition is fixed, and an `abs` is added to mimic the original MAM4 Fortran code.
This fix enabled stable long-term CIME simulations at high resolutions, such as ne120 and ne256.
[NBFB]
> Adds logic to avoid very small numbers for dryvol

- src/mam4xx/mo_chm_diags.hpp
- src/validation/mo_chm_diags/CMakeLists.txt
- src/validation/mo_chm_diags/chm_diags.cpp
- src/validation/mo_sethet/gas_washout.cpp
Fixing the `524 - validate_gas_washout_merged (Failed) ` and `492 - validate_chm_diags_ts_355 (Failed)` tests in Frontier.
> Fixing gas washout test for Frontier.

- scripts/quick_ne4pg2_cime_test_frontier.sh
This script is designed to be run quickly to test an EAMxx branch with any MAM4xx branch. It requires only two user inputs:
```
readonly E3SM_BRANCH="overfelt/eamxx/so4_h2so4_diagnostics"
readonly MAM4XX_BRANCH="main"
```
Once we run the script(`$ bash quick_ne4pg2_cime_test_frontier.sh`), it builds and submits the model to the queue.
> Adds a script to quickly test MAM4xx branches on Frontier

- scripts/quick_ne4pg2_cime_test_frontier.sh
Earlier, the script forced the user to remove the existing E3SM clone. This version uses the existing E3SM clone and hard reset branches after fetching the latest changes from the origin. A few echo messages are now color-coded.
> Use existing E3SM repo if it exists and hard reset branches

- src/mam4xx/mo_gas_phase_chemdr.hpp
Barriers cannot be inside a nested pfor loop.
Removing this line resolves a hang I am observing when running an eamxx test with the new EKAT. I have no idea why this is not causing a hang in master.
> Remove wrong team barrier in perform atm chem/micro

- build-haero.sh
This is so minor as to be trivial, yet... I still forget every once in a while to capitalize `Debug` or `Release`. This fixes that so first-letter capitalized or lowercase are both accepted. Goofy options, however, like `dEbUG` are not handled, so you are on your own for those 🙂
> Auto format build-type string

- src/mam4xx/aero_model.hpp
- src/mam4xx/wet_dep.hpp
- src/validation/aero_model/aero_model_wetdep.cpp
Yet another change to a function signature in order to be able to set these values form the E3SM input.
> Expose the activation fractions to make them settable from E3SM.

- .github/workflows/gh_gcc-cpu.yml
- src/validation/aero_emissions/CMakeLists.txt
- src/validation/aero_model/CMakeLists.txt
- src/validation/aerosol_optics/CMakeLists.txt
- src/validation/aging/CMakeLists.txt
- src/validation/calcsize/CMakeLists.txt
- src/validation/coagulation/CMakeLists.txt
- src/validation/convproc/CMakeLists.txt
- src/validation/drydep/CMakeLists.txt
- src/validation/gas_chem/CMakeLists.txt
- src/validation/hetfrz/CMakeLists.txt
- src/validation/lin_strat_chem/CMakeLists.txt
- src/validation/micro_gasaerexch/CMakeLists.txt
- src/validation/mo_chm_diags/CMakeLists.txt
- src/validation/mo_drydep/CMakeLists.txt
- src/validation/mo_photo/CMakeLists.txt
- src/validation/mo_setext/CMakeLists.txt
- src/validation/mo_sethet/CMakeLists.txt
- src/validation/mo_setinv/CMakeLists.txt
- src/validation/mo_setsox/CMakeLists.txt
- src/validation/modal_aero_amicphys_subareas/CMakeLists.txt
- src/validation/ndrop/CMakeLists.txt
- src/validation/nucleate_ice/CMakeLists.txt
- src/validation/nucleation/CMakeLists.txt
- src/validation/rename/CMakeLists.txt
- src/validation/tracer_data/CMakeLists.txt
- src/validation/tropopause/CMakeLists.txt
- src/validation/water_uptake/CMakeLists.txt
- src/validation/wetdep/CMakeLists.txt
Brings in the new python script for validation test comparison. Employs relative error for pass/fail criteria and adds optional args for extra debug info.
The important details are:
- There are quite a few tests that fail based on relative error, and I've included a list below.
- The convention is `Tol <old-abs-tol> -> <new-rel-tol-for-passing>  - <test number>   -   <test name>`
- Some tests are showing very high levels of relative error, indicating there may be major issues with the associated code.
- I have denoted those with `***asterisks***`
- This presents a tricky issue given the following, somewhat competing goals:
1. Merging PRs should not have failing tests.
2. We would like to maintain the previous results, based on absolute error, as a form of regression checking.
3. The tests …
> ff mam x validation for new compare script
